ZSH_THEME=powerlevel10k/powerlevel10k

export ZSH="$HOME/.oh-my-zsh"


HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=7

ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

DISABLE_UNTRACKED_FILES_DIRTY="true"

HIST_STAMPS="yyyy-mm-dd"

plugins=(
  git
  common-aliases
  docker
  extract
  history
  python  
  vscode
)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

. $HOME/.zsh/aliases.zsh
. $HOME/.zsh/environment.zsh
. $HOME/.zsh/functions.zsh
. $HOME/.zsh/path.zsh